name: ms_taxi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  geolocator: ^10.1.0
  get_it: ^7.6.4
  go_router: ^8.0.5
  hive: ^2.2.3
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  permission_handler: ^11.0.0
  wakelock: ^0.6.2

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/font/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/font/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter/Inter-Bold.ttf
          weight: 600
        - asset: assets/font/Inter/Inter-Bold.ttf
          weight: 700
